import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import TokenForm from "@/components/TokenForm";
import { useEffect, useState } from "react";
import { getAlgodClient } from "../clients";

const network = process.env.NEXT_PUBLIC_NETWORK || "SandNet";
const algodClient = getAlgodClient(network);

export default function Home() {
  const [availableTokens, setAvailableTokens] = useState(0);

  useEffect(() => {
    updateAvailableTokens();
  }, []);

  const updateAvailableTokens = async () => {
    // write code to display available tokens
    setAvailableTokens(0);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div>
          <h1 className="text-5xl mb-4">Buy TESLA Tokens</h1>
          <h4 className="mb-4">Network: {network}</h4>
          <h4 className="mb-4">Available Tokens: {availableTokens}</h4>
        </div>
        <TokenForm onPurchase={updateAvailableTokens} />
      </main>
    </>
  );
}
